// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectionUpdateParams = { id: string, name: string | null, socket_type: string | null, socket_address: string | null, is_default: boolean | null, };
