// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DockerConnection } from "./DockerConnection";

export type ConnectionRequestResponse = { data: DockerConnection | null, error: string | null, };
