// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectionCreateParams = { name: string, socket_type: string, socket_address: string | null, is_default: boolean | null, };
