// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerFileInfo } from "./ContainerFileInfo";

export type ContainerLsResponse = { items: Array<ContainerFileInfo>, count: number | null, dirs: number | null, files: number | null, };
