// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContainerSummary = { id: string, name: string, image: string, command: string, state: string | null, status: string | null, created: string | null, };
