// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerHostInfo } from "./ContainerHostInfo";

export type ContainerHostInfoResponse = { host: ContainerHostInfo | null, };
