// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContainerStopResponse = { status: string | null, error: string | null, state: string | null, };
