// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerDiff } from "./ContainerDiff";

export type ContainerDiffResponse = { diffs: Array<ContainerDiff> | null, error: string | null, };
