// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContainerExecParams = { id: string | null, cmd: string, tty: boolean | null, stdout: boolean | null, stdin: boolean | null, stderr: boolean | null, detach: boolean | null, stream: boolean | null, socket: boolean | null, privileged: boolean | null, demux: boolean | null, environment: string | null, workdir: string | null, user: string | null, };
