// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContainerFileInfo = { name: string | null, file_type: string | null, owner: string | null, group: string | null, size: number | null, created: string | null, modified: string | null, perm: string | null, is_dir: boolean | null, path: string | null, parent: string | null, real_path: string | null, id: string | null, };
