// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortBinding } from "./PortBinding";

export type ContainerRunParams = { image: string, name: string | null, cmd: string | null, tty: boolean | null, stdin: boolean | null, stdout: boolean | null, stderr: boolean | null, interactive: boolean | null, detach: boolean | null, expose_all_ports: boolean | null, auto_remove: boolean | null, user: string | null, env: Array<string>, working_dir: string | null, shell: string | null, mounts: Array<string> | null, ports: { [key: string]: PortBinding } | null, };
