// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortBinding } from "./PortBinding";

export type ContainerHostInfo = { hostname: string | null, user: string | null, ssh: PortBinding | null, ip: string | null, ls: string | null, };
