// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerSummary } from "./ContainerSummary";

export type ContainerGetResponse = { data: ContainerSummary | null, error: string | null, };
