// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerTopBody } from "./ContainerTopBody";

export type ContainerTopResponse = { top: ContainerTopBody | null, error: string | null, };
