// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MountPoint } from "./MountPoint";
import type { PortBinding } from "./PortBinding";
import type { Struct } from "./Struct";

export type ContainerRunParams = { image: string, name: string | null, cmd: string | null, tty: boolean | null, stdin: boolean | null, stdout: boolean | null, stderr: boolean | null, interactive: boolean | null, detach: boolean | null, expose_all_ports: boolean | null, auto_remove: boolean | null, user: string | null, env: Array<string>, working_dir: string | null, shell: string | null, binds: Array<string> | null, volumes: { [key: string]: MountPoint } | null, port_bindings: { [key: string]: Array<PortBinding> } | null, exposed_ports: { [key: string]: Struct } | null, explorable: boolean | null, ssh: boolean | null, };
