// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerPruneReport } from "./ContainerPruneReport";

export type ContainerPruneResponse = { report: ContainerPruneReport | null, error: string | null, };
