// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContainerHostInfoQueryParams = { id: string, hostname: boolean | null, user: boolean | null, ssh: boolean | null, ip: boolean | null, ls: boolean | null, };
