// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageSummary = { id: string, repo: string | null, created: string | null, size: string | null, };
