// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageBuildParams = { path: string, tag: string | null, quiet: boolean | null, };
