// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImagePruneReport } from "./ImagePruneReport";

export type ImagePruneResponse = { report: ImagePruneReport | null, error: string | null, };
