// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImagePullResponse = { repo: string | null, error: string | null, status: string | null, logs: string | null, };
