// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeleteResponse } from "./DeleteResponse";

export type ImagePruneReport = { Images: Array<DeleteResponse> | null, SpaceReclaimed: number | null, };
