// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MountPoint = { mount_type: string | null, source: string, destination: string, };
