// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetworkSummary = { id: string | null, name: string | null, created: string | null, ports: Array<string> | null, };
