// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortBinding } from "./PortBinding";

export type PortBindings = { bindings: { [key: string]: PortBinding }, };
