// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TermExecParams = { title: string | null, cwd: string | null, cmd: string | null, user: string | null, host: string | null, port: string | null, };
