// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VolumeSummary = { id: string | null, name: string | null, created: string | null, mount_point: string | null, };
